### ISSUE TITLE
ValueError: invalid null reference in method 'BOARD_ITEM___eq__', argument 2 of type 'BOARD_ITEM const &'

### ISSUE THREAD

**Issue by knaegt** [zykrah/kicad-kle-placer#15]
Hi! I'm trying to run the KLE plugin, but whenever I do, I get this message:
```
Traceback (most recent call last):

File "/Users/svamp/Documents/KiCad/8.0/3rdparty/plugins/com_github_zykrah_kicad-kle-placer/kle_placer_action.py", line 514, in Run
placer.Run(dlg.get_key_annotation_format(), dlg.get_stabilizer_annotation_format(), dlg.get_diode_annotation_format(), dlg.get_move_diodes_bool(), dlg.get_relative_diode_bool(), dlg.get_specific_ref_mode_bool())

File "/Users/svamp/Documents/KiCad/8.0/3rdparty/plugins/com_github_zykrah_kicad-kle-placer/kle_placer_action.py", line 296, in Run
first_key = self.get_footprint(key_format.format(1))

File "/Users/svamp/Documents/KiCad/8.0/3rdparty/plugins/com_github_zykrah_kicad-kle-placer/kle_placer_action.py", line 136, in get_footprint
if footprint == None and required:

File "/Volumes/sol2/Apps/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pcbnew.py", line 9450, in __eq__
return _pcbnew.BOARD_ITEM___eq__(self, aItem)

ValueError: invalid null reference in method 'BOARD_ITEM___eq__', argument 2 of type 'BOARD_ITEM const &'
```

For reference, I'm using KiCad 8.0.3 on an M1 mac, running Sonoma 14.5, and I renamed the switches to MX instead of the default SW. I used marbastlib footprints for the hotswap switches and default library footprints for the rest. The layout is a custom version of a 40% keyboard where the bottom row isn't as wide as the rest of the keyboard.

**Comment by zegonix** [comment]
I use manjaro (xfce) and used the plugin with kicad 7 earlier this year. kicad automatically updated to version 8 and now even after a clean and reinstall the plugin won't work (I tested the exact same situation as in kicad 7). I would assume that this is a version mismatch problem?
best regards, zegonix

**Comment by Tharun-jaji** [comment]
Hey, I had the same issue placing footprints in the PCB editor.

[https://github.com/zykrah/kicad-kle-placer/issues/11#issuecomment-1754116260](url)

This basically fixed it for me. 
Hope it helps.

**Comment by LightTreasure** [comment]
To expand on @Tharun-jaji 's comment above:

The issue is indeed due to kicad 8. On line no. 136 in `kle_placer_action.py`, the `==` needs to be replaced with the `is` keyword. I manually made this change in the file and restarted kicad. To find where the file is located for your installation, you can look at the error message.

Alternatively, since this change has already been committed into the repository via pull request #14 , you can just download `kle_place_action.py` from the PR and replace the one for your install. Restart kicad.

**Comment by zykrah** [comment]
I have since pushed the change to the PCM. Sorry it took so long!
